export const HTTP_STATUS_ERROR = 'HTTP_STATUS_ERROR'
export const TRANSLATOR = 'TRANSLATOR'

export const MAIN_INDUSTRY = 'MAIN_INDUSTRY'
export const SUB_ONE_INDUSTRY = 'SUB_ONE_INDUSTRY'
export const SUB_TWO_INDUSTRY = 'SUB_TWO_INDUSTRY'
export const SUB_THERE_INDUSTRY = 'SUB_THERE_INDUSTRY'
export const SUB_FOUR_INDUSTRY = 'SUB_FOUR_INDUSTRY'
export const GET_CUSTOMER_DATAS = 'GET_CUSTOMER_DATAS'

export const GET_LANGUAGE = 'GET_LANGUAGE'
export const CUSTOMER = 'CUSTOMER'

export const DO_TERM_SAVE = 'DO_TERM_SAVE'
export const CORPUS_SAVE = 'CORPUS_SAVE'

export const FILE_UPLOADER = 'FILE_UPLOADER'
export const FILE_DETAIL = 'FILE_DETAIL'